### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#1]
ML app
- doing sentiment analysis on reviews (or other text based object)
- for suggesting new anime (Spotify for anime)

**Comment by calvh** [comment]
ML-app for suggesting new anime (Spotify for anime)

**Comment by calvh** [comment]
online shop for clothes

**Comment by calvh** [comment]
calorie tracker

**Comment by HamdiaA** [comment]
twitter/reddit chatting app

**Comment by HamdiaA** [comment]
How-To-Do-Something/Tutorial site (Like wikihow)

**Comment by calvh** [comment]
leetcode clone

**Comment by HamdiaA** [comment]
blog

**Comment by HamdiaA** [comment]
QA engine (similar to stackoverflow)

**Comment by calvh** [comment]
rock paper scissors game with chat function

socket.io

**Comment by calvh** [comment]
upload videos let people comment/rate

**Comment by calvh** [comment]
social network like facebook

**Comment by calvh** [comment]
watch videos together with friends (one person streams)

**Comment by calvh** [comment]
coderpad

**Comment by calvh** [comment]
word frequency count website (input URL, output table of word frequencies)

**Comment by calvh** [comment]
mood tracker

**Comment by nimra200** [comment]
tic tac toe

**Comment by calvh** [comment]
> tic tac toe

could even have 2 games (rock paper scissors) in one!

**Comment by HamdiaA** [comment]
Microlearning app

**Comment by calvh** [comment]
> Microlearning app

e.g., return 10 results from search engine on topic

**Comment by HamdiaA** [comment]
Daily desktop background (trending on google images, or reddit)

**Comment by calvh** [comment]
social media like instagram, but reply with gifs or videos

**Comment by nimra200** [comment]
> Daily desktop background (trending on google images, or reddit)
> 
> Based on interests (eg cats, movies)

We could add a word of the day feature too

**Comment by calvh** [comment]
dashboard for something

**Comment by calvh** [comment]
carbon footprint tracker

**Comment by calvh** [comment]
project idea generator

**Comment by calvh** [comment]
Hidden:
twitter/reddit chatting app
How-To-Do-Something/Tutorial site (Like wikihow)
aggregate wikihow links, youtube videos, blogs
leetcode clone with coderpad (solve problems together)
blog
QA engine (similar to stackoverflow)
