### ISSUE TITLE
[Week 1] Feedback

### ISSUE THREAD

**Issue by khattakdev** [calvh/mlh-final-project#105]
Hey Fellows 👋,

Apologies for being this much lately but you know the reason.
Here is feedback for previous week (week 1)

## GitHub Best Practices
Most of the things looks good here. Pull request, issues the workflow is pretty smooth and good. One thing that could be improve is the CI/CD part. I noticed some of the pull requests have some GitHub Actions failed but the pull requests are merged. You can add some strict rules like **make sure tests are passing before merging pull request**.

## Readme
I think the README could be improve further. What it has right now is the project requirements.
README are use for adding detail description about the project/repository. Here's a [repository](https://github.com/matiassingers/awesome-readme) which has list of awesome readmes or maybe you can use an [npm package](https://www.npmjs.com/package/readme-md-generator).

## Project Board
The project board looks a bit complex. It can be simplified further to improve the workflow and reduce the complexity. You can reduce it to `To do`, `In Progress`, and `Completed`.

**Comment by calvh** [comment]
@khattakdev thanks for the feedback

- I believe only 1 PR was merged for failed test but that was an error on GitHub
- Noted on README, @nimra200 is working on it
- Deleted Urgent column in kanban
