### ISSUE TITLE
Redesign Play page

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#123]

**Comment by HamdiaA** [comment]
![Redesign of the Play Page](https://user-images.githubusercontent.com/56453981/129426217-8e1fb495-2b4c-436e-a897-2d24fe6bea41.png)

General Draft redesign for Play page

**Comment by HamdiaA** [comment]
Element Descriptions:

- Add a logo where "RPS" is [Issue #124](#124). We can all brainstorm how it will look then design it
- Move "Rock! Paper! Scissors! Showdown" to navbar
- Move other two (Wins: , etc and Choose Game Type/Waiting Player) up a bit
- "Game type" and "Opponent" is under the opponent's pic/circle. Only says CPU or Opponent's name/id
- Play Against CPU/Human buttons moved under game choices beside "Play Again" Button
- Socket Status is the Red or green bar at the bottom (won't be 50:50 but fill the entire screen)
- Room Chatroom is at the bottom right corner and can minimize
- General Chatroom is moved to main page

Feel free to add any suggestions/feedback

**Comment by calvh** [comment]
Since we have so much vertical whitespace, I am planning to add the profile picture on top of the rock paper scissors image.

Also I will combine the general chatroom and the room chatroom, and color them differently.

**Comment by HamdiaA** [comment]
> ...I am planning to add the profile picture on top of the rock paper scissors image

Which profile pic and which rock paper scissors image do you mean?
> Also I will combine the general chatroom and the room chatroom, and color the respective messages differently.

Sounds good!

**Comment by calvh** [comment]
Related to #104
