### ISSUE TITLE
Design logo that will go in the top left of the navbar and maybe the homepage

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#124]

**Comment by HamdiaA** [comment]
Here are two ideas for the logo that I designed. Let me know what you think (if I should make any changes or if I should do something completely different)

**# 1:**
![rpslogo1](https://user-images.githubusercontent.com/56453981/130071466-59333e92-5e29-410d-927e-b957e3e2fb0f.jpg)

**# 2:**
![rpslogo2](https://user-images.githubusercontent.com/56453981/130071479-c1571da4-9949-46b1-851d-55b3434017d6.jpg)

**Comment by calvh** [comment]
Looks great!

**Comment by HamdiaA** [comment]
Updated Design to be on the navbar:

![rpslogo3](https://user-images.githubusercontent.com/56453981/130269238-ae6cde81-8e8c-420d-935c-b2ef36749618.png)

**Comment by HamdiaA** [comment]
> Looks great!

Thanks!
