### ISSUE TITLE
Change project name to something that sounds good

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#128]
I think its time to change the repo name

I vote for rock-paper-scissors

Related to #127

**Comment by HamdiaA** [comment]
How about Rock-Paper-Scissors?

**Comment by calvh** [comment]
> How about Rock-Paper-Scissors?

It looks nicer but I prefer all lowercase so I don't have to press shift when I type the repo name!

That can be the official name in the README though like, "Rock Paper Scissors".
 
What about Rock Paper Scissors Redux?

Or RPS Redux
