### ISSUE TITLE
Feedback [Week 2]

### ISSUE THREAD

**Issue by khattakdev** [calvh/mlh-final-project#129]
Hey Fellows 👋

## ReadMe
This feedback was given last week, so I won't go into many details but the `readme` is to describe the project. This might be on the to-do list but this is just a reminder.

There isn't anything else noticeable at the moment but I would like to emphasize what needs to be achieved next week.

- [x] Update Readme
- [x] Refactor the code
- [x] Write some tests
- [x] Make a demo video

Remember, this week is to finalize everything and to ensure everything is working correctly. So please make sure you focus on the current codebase rather than introducing new features.

**Comment by calvh** [comment]
@khattakdev

Thank you for the comments. For "Refactor the code", do you have a specific section in mind? Or is it something you say because you know that every project will have messy code so you insert it as a generic comment that you know always be always true?

**Comment by khattakdev** [comment]
@calvh It's more of a second point. In hackathons, people are focused on the end goal rather than writing good code. So they always end up writing messy code or just code that works. 
It's a good idea to go through the whole code sample and see what parts can be improved further. Also, I believe you need to work on the folder layout as well, as the nginx folders don't make much sense.
