### ISSUE TITLE
Tie auth system to game and socketio

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#21]
How to tie to game?

How should the use of usernames be incorporated into socketio and the chat rooms?

**Comment by HamdiaA** [comment]
- Wins (2), Loses (0), Draw (1)
- ^ all under each user

**Comment by calvh** [comment]
```
{
  username: "Hamdia",
  password: "cats",
  wins: 1,
  losses: 1,
  draws: 1
}
```

**Comment by calvh** [comment]
Use sessions to store username

https://overiq.com/flask-101/sessions-in-flask/
