### ISSUE TITLE
Decide on domain name

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#25]
Come up with a list of candidates to try

**Comment by calvh** [comment]
I suggest any of the below, optionally in combination with `mlh` (prefix or suffix), `mlh-` (prefix) or `-mlh` (suffix)

```
rps
rockpaperscissors
rochambeau
roshambo
ro-sham-bo
```

and with top-level domain being `.com`, `.io`, `.tech`, `.ai`

I got the last 3 from [Wikipedia](https://en.wikipedia.org/wiki/Rock_paper_scissors)

Please edit this post with any desired changes or thumbs up if you approve
@nimra200 @HamdiaA @Rebecca-CYLi

**Comment by Rebecca-CYLi** [comment]
Agreed, should have a mlh (prefix or suffix) combo in it.

**Comment by HamdiaA** [comment]
I like the first two with the mlh suffix. Also we can get a .tech domain name from mlh

**Comment by calvh** [comment]
try rps.tech

if not, try mlh-rps.tech

**Comment by calvh** [comment]
wei: "duckdns should work but .tech is encouraged."

**Comment by nimra200** [comment]
Got domain name: mlh-rps.tech
