### ISSUE TITLE
Decide on DOM update method

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#59]
To update the DOM, we have several options:

- use vanilla Javascript
- use jQuery
- use a frontend framework like React
- use Flask and a library like turbo-flask https://turbo-flask.readthedocs.io/en/latest/quickstart.html#how-to-add-to-your-project

I'm leaning towards jQuery because:
- it's easy to learn and use
- vanilla JS is verbose and could be cumbersome
- React takes time to learn
- I've never used turbo-flask

Please share your thoughts.

**Comment by HamdiaA** [comment]
jQuery!
