### ISSUE TITLE
Investigate if it is necessary to check for collision between uuid4 and socketids

### ISSUE THREAD

**Issue by calvh** [calvh/mlh-final-project#99]
Code in `events.py` under `handle_queue` function

**Comment by Rebecca-CYLi** [comment]
Use both, they will not collide.

socketio's request.sid is for uniquely identifying a session, not a user

uuid4 is for uniquely identifying user[id]

**Comment by calvh** [comment]
my concern was that the ids are generated by unrelated code: socket IDs are handled by socketio and room ids by uuid4, so i was just wondering if by chance an id generated by uuid4 would be equal to a socket id generated by socket io

anyway, it is just an O(1) check so it's not an issue for now
